minhphan156/Abode

- front_end/package.json
- front_end/public/index.html
- front_end/src/App.css
- front_end/src/App.js
- front_end/src/components/booking/BookingBreakdownTable.js
- front_end/src/components/booking/BookingDetailsCard.js
- front_end/src/components/booking/Confirmation.js
- package.json
Confirmation Page Utopia, no more eyesore from staring at an auto parts invoice! Satisfaction Guaranteed!!
To cook up this stew, I created a booking folder and mixed 1/3 tablespoon each of BookingBreakdownTable.js, Confirmation.js and BookingDetailsCard.js. Not forgetting a dash of salt 😉
To spice things up, I went to the spice market and added them to the stew…mmm enjoy~
To adjust to your liking, navigate to the root and front_end directories to do an npm install.
> SJSU-1016, Implement Confirmation Page

- models/Hotel.js
> SJSU-1008, Create database schema for hotel

- models/booking.js
- models/customer.js
- routes/api/bookin.js
- server.js
- validation/checkAvalibility.js
frontend pass to backend end the booking information and backend pass back the result, success or fail.
frontend pass to backend:
{
"hotelID":"",
"roomType":"",
"checkIn":"",
"checkOut":"",
"numberRooms":,
"Firstname":"",
"Lastname":"",
"email":"",
"subtotal":,
"discounts":
}
backend pass back:
success:{
bookingID:
},
fail: {
error1:"You are not allow to make multilple reservation for same check in date"
},
{
error2:"No rooms avaliable for this hotel in our website anymore"
}
> SJSU-1018, Backend for Booking a Room 

- routes/api/hotels.js
- server.js
- validation/checkAvailableHotels.js
- validation/checkAvailibility.js
- validation/checkAvalibility.js
Endpoint to test: `localhost:5000/api/hotel/search`
Search test input data: (Raw JSON)
```
{
"destinationName":"san",
"checkIn":"2019-3-7",
"checkOut":"2019-3-8",
"numberRooms":5,
"numResults":12,
"lastIndex":0
}
```
`lastIndex` is where in the list of hotels to start searching (used for next/prev page button). `numResults` describes how many results to display at a time
> SJSU-1017 - Search Overview with Page/Result Tracking

- front_end/src/actions/authActions.js
- front_end/src/components/layout/Navbar.js
- front_end/src/components/searchResultOverview/searchResultOverview.js
- routes/api/users.js
What I did:
Made some very small changes to the backend code for login so that it includes the user's email in the response .json so that front end can access said email and show it in the navbar.
I also centered search result overview. (I AM NOT SURE IF IT WAS PURPOSELY NOT CENTERED BY DESIGN)
It will be very difficult to show the name of the user because 'name' isn't in the User schema. If we really need to show the name of the user, we'd have to change the User schema and thus backend API to include the user's name OR we'd have to make another backend call in addition to the login backend call just to get the user's name.
> SJSU-1043: Show User Email When Logged In & Centering Search Result Overview

- front_end/src/actions/searchResultActions.js
- front_end/src/components/indiv-hotel/IndivHotel.js
- package.json
maps can display correctly based on different hotel
> fix the maps

- front_end/src/components/landing_page/Landing.js
- front_end/src/components/layout/Navbar.js
> LANDING ANCHOR SCROLL FIX

- front_end/src/components/layout/Navbar.js
> Flipped 'Logout' and 'User email' positions in Navbar

- front_end/src/components/indiv-hotel/IndivHotel.js
> Centered the search widget in individual hotel info page

- validation/register.js
The register user feature had already been updated. Nothing new was added to its action-redux workflow.
I did however add some new stuff to validation for the 'firstname' and 'lastname' fields of register user; and that's what this PR mostly contains.
> SJSU-1043: Update Register User Redux and Validation

- front_end/src/components/layout/Navbar.js
> remove SubmitQueryBug

- models/booking.js
- routes/api/bookin.js
Changing reservation backend
api address: `/api/booking/changeReservation`
test with query params:
bookingID:
newCheckIn: YYYY-MM-DD
newCheckOut: YYYY-MM-DD
newPrice: ( can be null )
> SJSU-1048_2, Change Reservation Backend

- front_end/package-lock.json
- front_end/src/components/landing_page/search_widget/SearchWidget.js
- routes/api/hotels.js
- routes/api/users.js
Implemented the sorting/filtering, please leave me any suggestions.
> SJSU-1039-Sorting/Filtering

- models/Hotel.js
- models/booking.js
- routes/api/bookin.js
- routes/api/hotels.js
- routes/api/profile.js
- routes/api/users.js
Update Hotel schema, booking schema. Database is filled with full items, some of the attribute change.
Please test all the function we have in the backend code:
searchOverview (query params) :
/api/hotel/search
{
destinationName:  (we have San Diego, San Fransico, Los Angeles, New York)
checkIn:2019-04-05
checkOut:2019-04-06
numResults:10
numberRooms:
lastIndex:0
pageNumber:"1"
},
Individual Result (query params):
api/hotel/individual
{
id:
checkIn:
checkOut:
numberRooms:
}
make reservation(raw json object):
/api/booking/confirm
{
"hotelID":"5ca41d80d882a2ecf4735625",
"checkIn":"2019-04-10",
"checkOut":"2019-04-11",
"numberRooms":1,
"Firstname":"Test",
"Lastname":"Guy",
"email":"test2@gmail.com",
"roomType":"studio",
"subtotal":80,
"discount":0,
}
change reservation(query params): …
> update schema, naming in backing code

- routes/api/bookin.js
- routes/api/landing.js
change error to message in bookin.js
> fix PR #148 

- front_end/src/components/landing_page/Landing.js
- front_end/src/reducers/landingReducer.js
> Updated Landing Page Redux to New Backend

- front_end/src/components/landing_page/search_widget/CalendarStyleOverride.css
- package-lock.json
- routes/api/bookin.js
To test, localhost:5000/api/booking/cancel
key: bookingID, value has to be the id of a booking.
> SJSU-1030 Reservation Cancellation 

- models/Hotel.js
- models/booking.js
- routes/api/bookin.js
update reward points system for login user,
update res.send to confirmation page
do a /api/user/login 
(query params)
{
email:
password:
}
to login first, copy the token and paste to 
/api/booking/confirm
Authorization, Bearer Token,
(raw json)
test with
{
hotelID,
roomType,
checkIn,
checkOut,
numRooms,
Firstname,
Lastname,
email,
subtotal,
discounts,
rewardPointsUsed: null or Number
rewardPointsEarned: null or Number
numberOfNights,
total,
taxesAndFees,
rewardDiscount,
}
if you put Number on rewardPointsUsed, check the DB for you account the rewardPoints reduce or not.
rewardPointsEarned should not increase rewardPoints in DB in this call
> Sjsu-1049_2,reward points system

- front_end/src/actions/profileActions.js
- front_end/src/actions/types.js
- front_end/src/components/payment/BookingInfo.js
- front_end/src/components/payment/PaymentPage.js
- front_end/src/reducers/profileReducer.js
paymentPage did not send rewardPointsEarned  and rewardPointsDiscount properly ( only if the user clicked the checkbox to apply rewards points at least once)
- fixed that
- also added an action to retrieve the rewardsPoints of the user (backend not ready yet tho)
> SJSU-1063, Cleanup Payment Page

- config/keys_prod.js
- email/confirmationEmail.js
- models/booking.js
- package-lock.json
- package.json
- routes/api/bookin.js
send confirmation email to customer.
can test using frontend or postman
Please put new keys_dev.js into config folder
/api/booking/confirm
Postman:
{
"hotelID":"5ca531fbd882a2f6275b09e8",
"checkIn":"2019-04-26",
"checkOut":"2019-04-31",
"numberRooms":1,
"Firstname":"Test",
"Lastname":"Testing",
"email":"",
"roomType":"single",
"subtotal":100,
"discount":0,
"rewardPointsUsed":null,
"total": 5000,
"numberOfNights": 1,
"rewardDiscount": null,
"taxesAndFees":80,
"rewardPointsEarned":null
}
> SJSU-1050, confirmation email

- front_end/src/components/payment/BookingInfo.js
hooked up redux's rewardsPoints to payment page.
> SJSU-1063, added rewards points

- routes/api/bookin.js
Updated Change reservation, change the new subtotal, new total, new tax and fees, new discount, new reward discount. If any of above change. If login use has new reward points change, it will also reflect the change. 
`api/booking/changeReservation`
raw json
`{
"bookingID":"5cc023766c5b295a9400cee6",
"newCheckIn":"",
"newCheckOut":"",
"newSubtotal":680,
"newTotal":775.2,
"newTaxesAndFees":95.2,
"newPointsEarned":7752,
"newPointsused":,
}`
newCheckIn, newCheckOut, and bookingID is required, rest is not. 
newPointEarned and newPointsused required login user.
> SJSU-1048_3 Update Change Reservation

- front_end/package-lock.json
- package-lock.json
- routes/api/bookin.js
- routes/api/hotels.js
- server.js
…or more stars no longer have singles
> SuiteSingleStars

- routes/api/bookin.js
Some city is not in cities collection yet, it will cause an error for the confirm booking, fix it by add a checking to it.
> booking bug fix

- email/checkout.js
- routes/api/bookin.js
add a parse int for receive reward point use and earned. 
tested with `/api/booking/confirm`
JSON object
`{
"hotelID":"5ca531fbd882a2f6275b081b",
"checkIn":"",
"checkOut":"",
"numberRooms":1,
"Firstname":"Test",
"Lastname":"Testing",
"email":"",
"roomType":"king",
"subtotal":100,
"discount":0,
"rewardPointsUsed":2300.34,
"total": 5000,
"numberOfNights": 1,
"rewardDiscount": null,
"taxesAndFees":80,
"rewardPointsEarned":5000.23
}`
it should return object with rewardPointsEarned and rewardPointsUsed with integer
> SJSU-2001, Store rewardspoints as integers

- front_end/src/components/indiv-hotel/IndivHotel.js
Added discounts to the indiv hotel page.
To test:
- try on mobile
- try on big screen
- try with a hotel with no discount
- try with a hotel with discount (go through landing's Deal of the Week)
> SJSU-1062_3, Cleanup Individual Hotel Page (Add Discounts)

- front_end/src/actions/cityActions.js
- front_end/src/actions/profileActions.js
- front_end/src/components/history/HistoryOverview.js
- front_end/src/reducers/profileReducer.js
- routes/api/bookin.js
> Fix empty user history + weather

- front_end/src/components/city/CityOverview.js
- front_end/src/components/city/WeatherCard.css
- front_end/src/components/city/WeatherCard.js
**In this PR**
Added color to temperatures
Created a .CSS file for font sizing in mobile window
Fixed temperature to integers only
> SJSU-1054_3 Weather Card Styling

- front_end/src/components/indiv-hotel/IndivHotel.js
- routes/api/hotels.js
- server.js
holiday sale on check in july 4th and check out july 5th
> SJSU-6666 holiday sale

- front_end/src/components/booking/Confirmation.js
display a message next to rewards point earned, saying that they won't be added until checkin (see history expansion table for example)
> SJSU-1064_2 

- front_end/src/actions/searchResultActions.js
- routes/api/hotels.js
change the geocode method to backend, done it in hurry, test it well
> Sjsu-6667， geocode problem cause infinity spinner in individual page

- front_end/src/components/history/CancellationPrompt.js
- front_end/src/components/history/ChangeReservation.js
- front_end/src/components/landing_page/Landing.js
- inspiration image text
and
Mobile version:
- change booking -> calendar doesn't show
- cancel booking -> pop up should be full screen, or at least bigger
> SJSU-1065_5, Cleanup History Page

- front_end/src/components/indiv-hotel/IndivHotel.js
- front_end/src/components/indiv-hotel/indivHotel.css
Individual Hotel Page book single room button is been fixed, should be clickable now!!! 
For like the 10 millions times ...
> SJSU-3001_1 Individual Hotel Page Book Single Room button

- email/checkout.js
- email/welcomeEmail.js
- routes/api/bookin.js
- routes/api/hotels.js
> Sjsu-6668 fix the tomorrow checkin issue

- front_end/src/components/auth/BookingNotLoggedIn.js
- front_end/src/components/auth/Login.js
- front_end/src/components/history/HistoryOverview.js
Pushing login page, searching history page, and travel history page footer to the bottom
> SJSU-8888 Pushing to footer to the bottom

- front_end/package-lock.json
- front_end/src/actions/cityActions.js
- front_end/src/components/city/WeatherCard.js
- package-lock.json
What I did:
Specified the weather API to only look at US cities. Weather forecasts should be accurate.
> Sjsu fix dumbass weather
